services:
  # app:
  #   build: .
  #   command: yarn run start:dev
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/usr/src/app
  #     # - ./node_modules:/usr/src/app/node_modules
  #   environment:
  #     - PORT=${PORT}
  #     - DB_HOST=${DB_HOST}
  #     - DB_PORT=${DB_PORT}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_DATABASE=${DB_DATABASE}
  #     - DB_USERNAME=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   ports:
  #     - 3000:3000
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "5m"

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

volumes:
  postgres_data:
    driver: local

networks:
  app:
    external: true
